---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to this online report.

Results shown here reflect data retrieved as of 25 February 2022.

You will find here the following content:

- Tabular data showing the baseline characteristics of the 34 evaluable patients up to the data cut-off date. [Click here](PHENOMENAL_dm_2022-03-18.html) to see the analysis.

- [To be added] Preliminary efficacy results showing the current status of the study's primary endpoint:

    - Overall Response Rate (ORR) of intracraneal lesions as per RANO-BM criteria.

- [To be added] Preliminary efficacy results showing the current status of the study's secondary endpoint

    - Overall Response Rate (ORR) of intracraneal lesions as per RECIST v.1.1 criteria.

    - Overall Response Rate (ORR) of extracraneal lesions as per RECIST v.1.1 criteria.

    - Overall Response Rate (ORR) of all lesions (intra- and extracraneal) as per RECIST v.1.1 criteria.

    - Progression-Free Survival (PFS)

    - Overall Survival (OS)
